### ISSUE TITLE
side-by-side tables do not seem to be supported

### ISSUE THREAD

**Issue by kostrzewa** [haozhu233/kableExtra#143]
As described at https://stackoverflow.com/questions/38036680/align-multiple-tables-side-by-side , kable can be used to format tables in a single float side-by-side by placing the data frames into a list.

Unfortunately, when this kind of kable is piped to kableExtra functions, LaTeX complains:

```
! LaTeX Error: Not in outer par mode.
```

Here's an MWE:

## Rmd document header
```
---
title: "kableExtra_side_by_side"
author: Bartosz Kostrzewa
date: "2018-02-27"
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage[table]{xcolor}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage[normalem]{ulem}
output:
  pdf_document:
    citation_package: biblatex 
    latex_engine: lualatex
    highlight: tango
    keep_tex: no
    toc: true
    toc_depth: 2
bibliography: skeleton.bib
link-citations: yes
mainfont: XCharter
tables: true
---
```

## R code
```{r}
library("knitr")
library("kableExtra")

t1 <- mtcars[1:10,1:3]
t2 <- mtcars[11:20,1:3]

# this works
kable(list(t1,t2),
      format = "latex",
      booktabs = TRUE)

# this works too, as expected
kable(t1,
      format = "latex",
      booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped"))

# this fails
kable(list(t1,t2),
      format = "latex",
      booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped"))
```
