### ISSUE TITLE
loading kableExtra breaks inline R code in YAML header

### ISSUE THREAD

**Issue by sjpierce** [haozhu233/kableExtra#16]
I've been using a YAML header in my R markdown document (*.Rmd) that inserts headers and footers. My left footer uses inline R code to display the path and filename of the PDF file that will result when the file is knitted in R studio. I discovered today that loading the kableExtra package breaks that inline code and causes the code itself to display rather than the result of the code. Commenting out the library(kableExtra) line in the code below corrects the footer to show the path instead of the inline code that supposed to generate it. 

Code for reproducing the problem is below. 

```
---
output:
  pdf_document:
    latex_engine: xelatex
header-includes:
- \usepackage{fancyhdr}
- \usepackage[yyyymmdd,hhmmss]{datetime}
- \usepackage{lastpage}
- \usepackage{fontspec}
- \pagestyle{fancy}
- \lhead{Left header}
- \rhead{\today\ \currenttime}
- \cfoot{ }
- \fancyfoot[RE,RO]{\thepage\ of \pageref*{LastPage}}
- \renewcommand{\headrulewidth}{0.4pt}
- \renewcommand{\footrulewidth}{0.4pt}
- \fancypagestyle{plain}{\pagestyle{fancy}}
- \lfoot{\texttt{\small \detokenize{`r sub(".Rmd", ".pdf", knitr:::current_input(dir=TRUE))`}}}
---

# Setup 
``` {r global_options}
# Global chunk options (must be a stand-alone initial R chunk). 
knitr::opts_chunk$set(include  = TRUE, echo = TRUE, error = TRUE, 
                      message = TRUE, warning = TRUE)
```

``` {r load_packages}
library(knitr)            # for kable().
library(kableExtra)       # For formatting tables made by kable().
```
```
