### ISSUE TITLE
left-align table caption

### ISSUE THREAD

**Issue by HenrikEckermann** [haozhu233/kableExtra#194]
Thanks for this awesome package haozhu233!

I wanted to ask or otherwise note:

Is there a way to left-align the table caption? If I specify a caption, it is always centered above the table. I would prefer this in exactly this way! However, for a paper in APA6th they expect me to leftalign the table caption. Is there a way to do this with kableExtra?

**Comment by HenrikEckermann** [comment]
Maybe as a temporary solution for those who need this to make tables/figures apa6th style:

For me this worked in Rmarkdown:
1. Specify header.tex as follows:
```
\usepackage{caption}

\DeclareCaptionLabelSeparator*{spaced}{\\[2ex]}
\captionsetup[table]{textfont=it,format=plain,justification=justified,
  singlelinecheck=false,labelsep=spaced,skip=0pt}
\captionsetup[figure]{labelsep=period,labelfont=it,justification=justified,
  singlelinecheck=false,font=doublespacing}
```

2. Include this in your YAML header:
```
documentclass: "article"
header-includes:
   - \usepackage{booktabs}
   - \usepackage{multirow}
   - \usepackage{setspace}
   - \usepackage{subcaption}
   - \usepackage{caption}
   - \usepackage{tikz}
   - \usepackage{float}
   - \usepackage{setspace}
output: 
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: header.tex
```
Then e.g. a table like this worked for me:

```
kable(norm_table, booktabs = T, caption = "Normality Statistics", escape = F) %>%
  kable_styling(latex_option = c("hold_position"), position = "left")
```

The `escape = F` is not required but was required here for other reasons.

It maybe that not everything is requires (e.g. I think kableExtra load booktabs anyway). This works for me to make tables completely apa6th conform (I struggle though with linebreaks that I need for longer line but saw new linebreak functionality in kableExtra so maybe I can figure out a way!)

kableExtra is really very useful. Please keep up the good work!
