### ISSUE TITLE
using kableExtra with R in fancyheader/footer causes pdf to fail to knit

### ISSUE THREAD

**Issue by betsan** [haozhu233/kableExtra#296]
**Describe the bug**

Loading the kableExtra package with R in a fancyheader/footer causes the pdf to fail to knit with the following error:

````
! Missing $ inserted.
<inserted text> 
                $
l.165 \end{document}

Error: Failed to compile test.tex. See test.log for more info.
Execution halted
````

Commenting out the line to load kableExtra means the document knits as expected.

**To Reproduce**

````
--
title: "Example"
author: "Alice & Bob"
output:
  pdf_document:
date: '`r as.character(git2r::last_commit(git2r::repository("."))$author$when)`'
header-includes:
- \usepackage{longtable}
- \usepackage{fancyhdr}
- \usepackage{lastpage}
- \usepackage{booktabs}
- \pagestyle{fancy}
- \fancyhead[L]{`r as.character(git2r::last_commit(git2r::repository("."))$author$when)`}

---

#Firstpage
```{r setup, include=TRUE,message=FALSE,warning=FALSE}
library(kableExtra)
```

\clearpage

#Secondpage

````

**Comment by jdbarillas** [comment]
Hi @betsan 

I got your code to work by switching my latex engine to `xelatex` instead of `pdflatex` (the default), which provides you with a short-term solution. Not sure why kableExtra would have a problem with `pdflatex` though.

```
--
title: "Example"
author: "Alice & Bob"
output:
  pdf_document: 
    latex_engine: xelatex # Change is made here
date: '`r as.character(git2r::last_commit(git2r::repository("."))$author$when)`'
header-includes:
- \usepackage{longtable}
- \usepackage{fancyhdr}
- \usepackage{lastpage}
- \usepackage{booktabs}
- \pagestyle{fancy}
- \fancyhead[L]{`r as.character(git2r::last_commit(git2r::repository("."))$author$when)`}

---
```
