### ISSUE TITLE
Figure caption above does not work when using KableExtra

### ISSUE THREAD

**Issue by Nico-Rojas** [haozhu233/kableExtra#351]
Hi!
First of all, thank you @haozhu233 for your package. kableExtra is awesome. 

**Issue**
Once I use kableExtra I can no longer write Figure's caption on top. 

Some people have suggested solutions (for example this post (https://stackoverflow.com/questions/53194514/how-to-move-the-caption-of-a-figure-from-the-bottom-to-the-top ) 

However, the solution does not work. It seems as if kableExtra does not allow me to put captions on top of a figure. 

**To Reproduce**
Here is an example code.  
````
---
title: "Example"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
header-includes:
   - \usepackage{floatrow}
   - \floatsetup[figure]{capposition=top}
---
```{r fig1, echo=FALSE, fig.cap="My title"}
x <- 1:10
y <- 11:20
plot(x, y)
```
```{r kextra}
options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
kable(x, "latex") %>% kable_styling(latex_options = "striped") 
```
````

When I run it I get the error: "! Undefined control sequence. <recently read> \rowcolor".  Is there any way to control this issue? Maybe there is another way to put captions on top of figures in PDF which could be compatible with kableExtra I have look through many posts but every time there is an error ... 

I wish to keep using kableExtra, but it is harder when the ability to manage my tables hinders my ability to manage my figures ...

Best!
Nico.

**Comment by haozhu233** [comment]
Hi, @Nico-Rojas, not only you need to turn off the "auto load package", you will have to load them by yourself manually. 

In your case, you should load floatrow ahead of kableExtra's latex dependencies. 
````
---
title: "Example"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
header-includes:
   - \usepackage{floatrow}
   - \floatsetup[figure]{capposition=top}
   - \usepackage{booktabs}
   - \usepackage{longtable}
   - \usepackage{array}
   - \usepackage{multirow}
   - \usepackage{wrapfig}
   - \usepackage{float}
   - \usepackage{colortbl}
   - \usepackage{pdflscape}
   - \usepackage{tabu}
   - \usepackage{threeparttable}
   - \usepackage{threeparttablex}
   - \usepackage[normalem]{ulem}
   - \usepackage[normalem]{ulem}
   - \usepackage[utf8]{inputenc}
   - \usepackage{makecell}
   - \usepackage{xcolor}
---
```{r fig1, echo=FALSE, fig.cap="My title"}
x <- 1:10
y <- 11:20
plot(x, y)
```

```{r kextra}
options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
kable(x, "latex") %>% kable_styling(latex_options = "striped") 
```
````

You can use `kableExtra::kableExtra_latex_packages()` to bring up the list
