### ISSUE TITLE
table format is lost depending on output formats order in .Rmd file header

### ISSUE THREAD

**Issue by abubelinha** [haozhu233/kableExtra#470]
When I need to produce several formats at the same time, I am using [this approach](https://stackoverflow.com/a/53280491/710788)  which is working for me pretty well (I hit _Ctrl+Shift+K_ just once, and I get new pdf, docx, html, odt & rtf formats from a single .Rmd file).

Nonetheless, in the case of `kableExtra` I wonder if the different **output formats are supposed to follow a given order?**.
I ask because I have found an issue when using the package for the first time.

**This works** (PDF output OK):

````
---
title: "Multiple formats"
author: "Me"
date: "15/4/2020"
output:
  pdf_document:
    toc: true
  word_document:
    toc: true
    reference_docx: wordLibreOfficeStyles.docx  
  html_document:
    toc: true
  odt_document: default
  rtf_document:
    toc: true
  latex_document: default
  #slidy_presentation: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "output", output_format = "all") })
urlcolor: blue 
---

```
{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```
{r}
library(kableExtra)
dt <- mtcars[1:5, 1:6]
kable(dt)
```
````

But if I change the order of output formats moving PDF after Word, **this fails** (PDF is produced, but the table format is lost). 

````
---
title: "Multiple formats"
author: "Me"
date: "15/4/2020"
output:
  word_document:
    toc: true
    reference_docx: wordLibreOfficeStyles.docx  
  pdf_document:
    toc: true
  html_document:
    toc: true
  odt_document: default
  rtf_document:
    toc: true
  latex_document: default
  #slidy_presentation: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "output", output_format = "all") })
urlcolor: blue 
---

```
{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```
{r}
library(kableExtra)
dt <- mtcars[1:5, 1:6]
kable(dt)
```
````

I attach both PDFs.

[toPdfWordOdtRtfLatex-GOOD.pdf](https://github.com/haozhu233/kableExtra/files/4500379/toPdfWordOdtRtfLatex-GOOD.pdf)
[toWordPdfOdtRtfLatex-BAD.pdf](https://github.com/haozhu233/kableExtra/files/4500381/toWordPdfOdtRtfLatex-BAD.pdf)

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_2.1

loaded via a namespace (and not attached):
 [1] compiler_3.6.3  htmltools_0.3.6 tools_3.6.3     rstudioapi_0.10 yaml_2.2.0     
 [6] Rcpp_1.0.1      pander_0.6.3    knitr_1.23      xfun_0.8        digest_0.6.20  
[11] evaluate_0.14  
> 
```

**Comment by abubelinha** [comment]
Nevermind. I found the solution [here](https://stackoverflow.com/a/60011624/710788):

https://stackoverflow.com/questions/60011425/kableextra-error-in-markdown-when-rendering-to-pdf/60011624#60011624

> You need to explicitly add format="latex" within the kable function (for example, kable(format="latex")) when using kableExtra with kable for PDF output. See [the kableExtra introduction](https://github.com/haozhu233/kableExtra#basic-usage) for additional information and examples.

So this is my working code now. No issues:

````
---
title: "Multiple formats"
author: "Me"
date: "15/4/2020"
output:
  word_document:
    toc: true
    reference_docx: wordLibreOfficeStyles.docx  
  pdf_document:
    toc: true
  html_document:
    toc: true
  odt_document: default
  rtf_document:
    toc: true
  latex_document: default
  #slidy_presentation: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "output", output_format = "all") })
urlcolor: blue 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

output_format <- knitr::opts_knit$get("rmarkdown.pandoc.to")
```

```{r, echo=FALSE}
if(! output_format %in% c("latex","html") ) {
  message = paste("*",output_format,
  "* format IS NOT COMPATIBLE with *kableExtra*",sep="")
} else {
  message = paste("This is a *kableExtra* table in *",output_format,
  "* format:",sep="")
}
```

## `r message`

```{r, echo=FALSE}
if(output_format %in% c("latex","html") ) {
  library(kableExtra)
  dt <- mtcars[1:5, 1:6]
  kable(dt,format=output_format)
}
```
````
