### ISSUE TITLE
collapse_rows() doesn't end up with vertically centred entry

### ISSUE THREAD

**Issue by EhrmannS** [haozhu233/kableExtra#56]
Hi!

I have the following example. It results in a table, where `car 1` is to be found somewhere in the 4th fifth of the vertical distribution, rather than directly in the middle. This creates for more complex tables and longer values in this "collapsed cell" rather strange behaviour and sometimes the text even crosses the lower boundary of the group. It seems almost as if the value would be centred between the two maximum border of the table per page, and not between the two borders of the group that should be collapsed.

```
---
documentclass: book
lof: no
lot: no
output:
  bookdown::pdf_book:
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
  bookdown::html_document2:
    fig_caption: yes
    theme: spacelab
subtitle: null
---
```

```{r setup, include = FALSE}
library(knitr)
library(magrittr)
library(bookdown)
library(captioner)
library(stringr)
library(dplyr)
library(kableExtra)
```

```{r testing, echo=FALSE}
long_dt <- cbind(car = row.names(mtcars), mtcars)
rownames(long_dt) <- NULL
long_dt[,1] <- c(rep("car 1", 22), rep("car 2", 10))

kable(long_dt, 
      longtable = T,
      format = "latex",
      booktabs = T, 
      caption.short = "An awesome \\textsc{Longtable}.",
      caption = "An awesome Longtable, with a caption.") %>%
  add_header_above(c(" ", "Group 1" = 5, "Group 2" = 6)) %>%
  kable_styling(latex_options = "repeat_header") %>%
  collapse_rows(columns = 1)
```

Even more strangely, if you set the line `long_dt[,1] <- c(rep("car 1", 22), rep("car 2", 10))` to `long_dt[,1] <- c(rep("car 1", 16), rep("car 2", 16))`, `car 2` is printed where the repeated header on the second page would be printed otherwise.

If I compile it to html it works without problems.
