### ISSUE TITLE
"striped" option conflicts with indentation from pack_rows in kable_styling 

### ISSUE THREAD

**Issue by kgconery** [haozhu233/kableExtra#571]
When the "striped" option is used in kable_styling, when knitting to a pdf, every gray row underneath each group is not properly indented.

File header, including latex engine:
```
---
title: "Untitled"
date: "12/7/2020"
output:
  pdf_document: 
    latex_engine: xelatex
    keep_tex: true
header-includes:
- \usepackage{multirow}
---
```

Code that generates the table:
```
knitr::opts_chunk$set(echo = TRUE)
library(latexpdf)
library(kableExtra)
kbl(mtcars[1:10, 1:6], caption = "Group Rows") %>%
  kable_styling(latex_options = c("striped")) %>%
  pack_rows("Group 1", 4, 7) %>%
  pack_rows("Group 2", 8, 10)
```

Results in the following table:
![Screenshot 2020-12-07 145932](https://user-images.githubusercontent.com/74117656/101415497-e2705b80-389c-11eb-8e9e-4265c031bccb.png)

Looking through the .tex file, it looks like every cell gets a gray shading, which seems to overwrite the `\hspace` used in each row of the packed rows:

```

\multicolumn{7}{l}{\textbf{Group 2}}\\
\hline
\hspace{1em}Merc 240D & 24.4 & 4 & 146.7 & 62 & 3.69 & 3.190\\
\hline
\cellcolor{gray!6}{Merc 230} & \cellcolor{gray!6}{22.8} & \cellcolor{gray!6}{4} & \cellcolor{gray!6}{140.8} & \cellcolor{gray!6}{95} & \cellcolor{gray!6}{3.92} & \cellcolor{gray!6}{3.150}\\
\hline
\hspace{1em}Merc 280 & 19.2 & 6 & 167.6 & 123 & 3.92 & 3.440\\
\hline

```

Is there a work around? Am I missing something? 

Thanks!
