### ISSUE TITLE
Hover with color doesn't work

### ISSUE THREAD

**Issue by englianhu** [haozhu233/kableExtra#617]
# Report bug

I tried to refer to [Is it possible to change the hover colour in kableExtra?](https://stackoverflow.com/a/49429306/3806250), but unable to hover with color

```css
<style>
.table-hover > tbody > tr:hover { 
  background-color: #8D918D;
}
</style>
````

# Error

1) Defalut hover with grey color

https://user-images.githubusercontent.com/7227582/118960250-100a1680-b99e-11eb-9722-3e60de6b1d59.mp4

2) Added color won't be able hover

https://user-images.githubusercontent.com/7227582/118960260-126c7080-b99e-11eb-882e-953960e56344.mp4

# Desired Outcome

Is it possible to make it similar with https://rpubs.com/englianhu/Stylist-Chunks?

https://user-images.githubusercontent.com/7227582/118975041-80b92f00-b9ae-11eb-945f-fd22ef9c1c20.mp4
