### ISSUE TITLE
Citations in tables do not render correctly

### ISSUE THREAD

**Issue by DanielIAvila** [haozhu233/kableExtra#896]
I am encountering a problem. I want to use kableExtra to produce a table that has references in one of the columns. I am using `rmarkdown` and the `YAML` header looks like below. 

```
---
title: ''
  
author:
  - First Last Name:
      email: last.name@domain.com
      institute: [xxx]
      correspondence: true
institute:
  - xxx: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::pdf_document2:
    toc: false
    keep_tex: true
    number_sections: true
    fig_caption: true
    latex_engine: xelatex
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
  bookdown::word_document2:
    toc: false
    number_sections: true
    fig_caption: true
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
  bookdown::html_document2:
    df_print: paged
    number_sections: true
    fig_caption: true
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
header-includes:
  - \usepackage{graphicx}    
  - \usepackage{longtable} 
  - \usepackage{pdflscape}   
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{fontspec}     
  - \setmainfont{Lato}        
  - \usepackage{setspace}     
  - \usepackage[left]{lineno} 
  - \linenumbers
  - \usepackage{hyperref}   
  - \usepackage{cleveref}   
  - \usepackage{float}     
    
bibliography: references.bib
compact-title: false 
link-citations: true
citation_package: biblatex
csl: "ecology-and-society.csl"
---
```

The `r chunk` for the table looks like (simplified)

```
```{r table2, echo=FALSE, results='asis', cache=FALSE}
library(knitr)
library(kableExtra)

# Create independently the columns
type <- c(
    "Some tex", rep("", 5),
    "More text", ""
)

category <- c(
    "A",
    "B",
    "C",
    "D",
    "E",
    "F"
)

description <- c(
    "Text 1",
    "Text 2",
    "Text 3",
    "Text 4",
    "Text 5",
    "Text 6"
)

references <- c("@ref1",    
                "@ref2",
                "@ref3",
                "@ref4",
                "@ref5",
                "@ref6"
)

# Construct dataframe
table <- data.frame(
  Type = type,
  Category = category ,
  Description = descriptions,
 References = references
)

kableExtra::kable(table, format = "markdown", booktabs = TRUE, escape = FALSE,
      caption = "Some caption here") %>%
  kable_styling(latex_options = c("striped", "hold_position"), position = "center", font_size = 10) %>%
  column_spec(3, width = "30em")
```

However, this prints the references as `@ref1`,  `@ref2` and so on. Is there a workaround for this problem?

**Comment by dmurdoch** [comment]
We usually recommend that you use `kbl()` instead of `kable()`, and let it work out the `format` setting.  Does that help?

**Comment by DanielIAvila** [comment]
The table compiles, but the references keep knitting as `@ref1`

**Comment by DanielIAvila** [comment]
My code from above suffices. I am providing five references to change for `@ref1` ...

```
@article{Abatzoglou2018,
  title = {{{TerraClimate}}, a High-Resolution Global Dataset of Monthly Climate and Climatic Water Balance from 1958--2015},
  author = {Abatzoglou, John T and Dobrowski, Solomon Z and Parks, Sean A and Hegewisch, Katherine C},
  year = {2018},
  month = jan,
  journal = {Scientific Data},
  volume = {5},
  pages = {170191},
  issn = {2052-4463},
  doi = {10.1038/sdata.2017.191},
}

@article{Acuto2018,
  title = {Building a Global Urban Science},
  author = {Acuto, Michele and Parnell, Susan and Seto, Karen C},
  year = {2018},
  month = jan,
  journal = {Nature Sustainability},
  volume = {1},
  number = {1},
  pages = {2--4},
  issn = {2398-9629},
  doi = {10.1038/s41893-017-0013-9},
}

@article{armstrongmckay2022Exceeding15degCGlobal,
  title = {Exceeding 1.5{$^\circ$}{{C}} Global Warming Could Trigger Multiple Climate Tipping Points},
  author = {Armstrong McKay, David I. and Staal, Arie and Abrams, Jesse F. and Winkelmann, Ricarda and Sakschewski, Boris and Loriani, Sina and Fetzer, Ingo and Cornell, Sarah E. and Rockstr{\"o}m, Johan and Lenton, Timothy M.},
  year = {2022},
  month = sep,
  journal = {Science},
  volume = {377},
  number = {6611},
  pages = {eabn7950},
  issn = {0036-8075, 1095-9203},
  doi = {10.1126/science.abn7950},
  langid = {english},
}

@article{rocha2018CascadingRegimeShifts,
  title = {Cascading Regime Shifts within and across Scales},
  author = {Rocha, Juan C and Peterson, Garry and Bodin, {\"O}rjan and Levin, Simon},
  year = {2018},
  journal = {Science},
  volume = {362},
  number = {6421},
  pages = {1379--1383},
  doi = {10.1126/science.aat7850},
  langid = {english},
}

@article{robles-bonilla2021AddressingThermalComfort,
  title = {Addressing Thermal Comfort in Regional Energy Poverty Assessment with Nussbaumer's {{MEPI}}},
  author = {{Robles-Bonilla}, Tiare and Cedano, Karla G.},
  year = {2021},
  journal = {Sustainability},
  volume = {13},
  number = {1},
  pages = {1--16},
  issn = {20711050},
  doi = {10.3390/su13010352},
}

```

**Comment by DanielIAvila** [comment]
Precisely, it does not run. Here is a working example. I changed from `kable` to `kbl` and I am using `tibble::tribble`. This is the only way I made it work. However, the table breaks and is not rendered in PDF when multiple citations are added in one row.

```
---
title: ''
  
author:
  - First Last Name:
      email: last.name@domain.com
      institute: [xxx]
      correspondence: true
institute:
  - xxx: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::pdf_document2:
    toc: false
    keep_tex: true
    number_sections: true
    fig_caption: true
    latex_engine: xelatex
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
  bookdown::word_document2:
    toc: false
    number_sections: true
    fig_caption: true
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
  bookdown::html_document2:
    df_print: paged
    number_sections: true
    fig_caption: true
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
header-includes:
  - \usepackage{graphicx}    
  - \usepackage{longtable} 
  - \usepackage{pdflscape}   
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{fontspec}     
  - \setmainfont{Lato}        
  - \usepackage{setspace}     
  - \usepackage[left]{lineno} 
  - \linenumbers
  - \usepackage{hyperref}   
  - \usepackage{cleveref}   
  - \usepackage{float}     
    
bibliography: references.bib
compact-title: false 
link-citations: true
citation_package: biblatex
csl: "ecology-and-society.csl"
---

```{r table, echo=FALSE, results='asis', cache=FALSE}

library(kableExtra)

tibble::tribble(
  ~Type, ~Category, ~Description, ~Reference,
"Alpha", "A",  "Some text", "@rocha2018CascadingRegimeShifts", 
"Beta",   "A",  "Some text", "@armstrongmckay2022Exceeding15degCGlobal, @Abatzoglou2018"
) |>
  kbl(format = "latex", escape = FALSE, booktabs = TRUE, caption = "\\makebox[\\textwidth][l]{Table caption goes here \\\\ \\textit{A caption table subtitle goes here.}}") |>
  kable_styling(latex_options = "striped", font_size = 10, position = "center") |>
  column_spec(3, width = "30em")
```
```

Check that `kbl(format = "latex")` needs to be changed to `kbl(format = "markdown")` for it to render in PDF. However, as I said, when using multiple references, it stops working.
